### ISSUE TITLE
Default values best practices

### ISSUE THREAD

**Issue by fluxxus** [zellwk/typi#1]
This is not really an issue, just looking for some help and tips for default styles.

What should be our starting point? `Normalize.css` , `sanitize.css`, meyer reset? Should we reset the `margin-top` for all paragraphs and headers, and just use `margin-bottom` for maintaining the vertical rhythm?

Basically, I am just looking for some best practices tips for the default styles, if there are some.

**Comment by zellwk** [comment]
It's really up to you. I personally do the following: 
1. use `normalize.css`
2. reset all `margin`s and `padding`s for `h1,h2,h3,h4,h5,h6, p`
