### ISSUE TITLE
How to integrate specific html tags into the typi map?

### ISSUE THREAD

**Issue by cywtf** [zellwk/typi#10]
I am currently doing 

```
html{
  @include typi-base();
}
```

and my paragraph tags `<p>` and mostly every other tag are correctly formatted. 
However, some specific tags such as `<code>` or `<pre>` are not included there. 

If I do:

```
code{
  @include typi-base();
}
```

The `<code>` tag looks completely messed up. 

What's the best approach here? Should I create another map just for this tag and duplicate the same styles I have defined in the `$typi` map? I would like to avoid duplication, if possible.

Thanks!

**Comment by zellwk** [comment]
You use the `typi` function instead of `typi-base()` for other maps. 

For example: 

```
$code: (0.8em, 1.2);

code {
  @include typi($code)
}
```
