### ISSUE TITLE
Undefined variable: "$base-font-size"

### ISSUE THREAD

**Issue by jimzarkadas** [zellwk/typi#11]
I noticed that there is a bug when using vr() function with 'px' values.

I have the following config:

```
$typi: (
  null: (18px, 26px),
  lg: 20px
);
```

and I get the following error:

```
Message:
    node_modules/typi/scss/typi/_typi.scss
Error: Undefined variable: "$base-font-size".
        on line 90 of node_modules/typi/scss/typi/_typi.scss
>>       @return $vr * $base-line-height / $base-font-size * 1rem;
   ----------------------------------------^
```

I dived into typi code and I noticed that you don't define the value of $base-font-size anywhere.

Cheers,
Jim

**Comment by zellwk** [comment]
Strange. I don't seem to get the same error. Can you put up a repo and send it over?

**Comment by DanielRuf** [comment]
This is likely an issue with compass and how long it takes to parse / load its default variables.
