### ISSUE TITLE
@error $breakpoint not found in $breakpoints

### ISSUE THREAD

**Issue by lomteslie** [zellwk/typi#2]
Hey there. I have the following sass:

```
$breakpoints: (
  xs:  320px,
  sm:  768px,
  md:  990px,
  lg:  1170px,
  xl:  1380px,
  xxl: 1700px
);

$h1-map: (
  null: ms(5),
  xl: ms(8)
)

...

h1 {
  font-weight: 300;
  @include typi($h1-map);
}
```

...and when everything runs I get the following error:

```
@error $breakpoint not found in $breakpoints;
     ^
      (null: 2.48832em, xl: 4.29982em) false in (xs: 320px, sm: 768px, md: 990px, lg: 1170px, xl: 1380px, xxl: 1700px)
      in /Users/tom/dev/health/health/assets/node_modules/typi/scss/typi/_typi.scss (line 17, column 7)
```

It says the breakpoint is not there, and yet it seems to be clearly there. Any thoughts? I'm running webpack w/ the latest version of sass-loader if that makes any difference. Thanks for any help.

**Comment by lomteslie** [comment]
Turns out the error was this missing semicolon:

```
$h1-map: (
  null: ms(5),
  xl: ms(8)
)
```

Thanks Sass... Sorry!

**Comment by zellwk** [comment]
Thanks for letting me know how this error happened! It's really interesting, and I'm glad you got it working :)
