### ISSUE TITLE
Issue with NPM version

### ISSUE THREAD

**Issue by mjs34** [zellwk/typi#20]
New to npm so apologies if I'm missing something completely obvious. The bower version works fine, but Codekit gives this error when attempting to compile the npm version:

Error: base not found in $typi map
        on line 21 of Projects/web-starter-kit-2/node_modules/typi/scss/private/breakpoints/_breakpoints.scss, in `_ty-write-breakpoints'
        from line 34 of Projects/web-starter-kit-2/node_modules/typi/scss/public/typi/_typi.scss, in `typi'
        from line 61 of Projects/web-starter-kit-2/node_modules/typi/scss/public/typi/_typi.scss, in `typi-base'
        from line 17 of Projects/web-starter-kit-2/app/styles/scss/main.scss
  Use --trace for backtrace.

Any info you can offer is appreciated. Thanks

**Comment by zellwk** [comment]
Seems like Codekit is trying to pull the latest unstable version (v3.0.0-alpha). Is there a way where you can get codekit to use a stable (or previous) version, like v2.3?

**Comment by mjs34** [comment]
Thanks for getting back. I am a little confused considering all the files generated by npm install point to the 3.0 alpha version. Should I manually change those files? Do I even need an external program to process the scss or is something built into Typi? I do see that the gulpfile.js inside node_modules> typi has gulp sass and I wondered if I should be using that to be process my scss. Again, still getting to grips with node/gulp etc, so sorry if I'm the wrong track entirely.

**Comment by zellwk** [comment]
Hmm. Might be my bad since it's my first time trying out an alpha build. Try `npm install typi@2.3.0

**Comment by aminta** [comment]
Me too I had same problem, the @zellwk solution works, thanks!

**Comment by mjs34** [comment]
Cool...glad to hear it. I haven't had a chance to test solution yet but
thanks to @zellwk for the response

**Comment by zellwk** [comment]
Closing since it's resolved
