### ISSUE TITLE
vr(...) with media queries?

### ISSUE THREAD

**Issue by strarsis** [zellwk/typi#24]
vr(...) by default uses REM units. How is the rhythm followed used by media queries? EM units would at least relative to the font-size by mediaquery, REM units are absolute.
Is there a vr(...) mixin that also generates the necessary breakpoints (like ms-respond(...)) from [modular-scale](https://github.com/modularscale/modularscale-sass#responsive-scales) by using the typi options?

**Comment by zellwk** [comment]
Rem aren't absolute. They're relative to the root font size. There's one, but it's only present in Typi V3. Aaaaand... it makes code super complex, so I recommend not even thinking about it.
