### ISSUE TITLE
Argument `$number` of `unitless($number)` must be a number

### ISSUE THREAD

**Issue by MatthewKosloski** [zellwk/typi#25]
Trying to use the modular scale function in a heading map like so:

```
$h1-map: (
	null: (32px, 1.2),
	large: (ms(2), 1.2)
);
```

But I get this error:

```
Message:
    node_modules/typi/scss/ty/_functions.scss
Error: argument `$number` of `unitless($number)` must be a number

       Backtrace:
       	node_modules/typi/scss/ty/_functions.scss:30, in function `unitless`
       	node_modules/typi/scss/ty/_functions.scss:30, in function `_ty-calc-font-size`
       	node_modules/typi/scss/ty/_functions.scss:15, in function `_ty-font-size`
       	node_modules/typi/scss/ty/_mixins.scss:65, in mixin `-ty-write-props`
       	node_modules/typi/scss/ty/_mixins.scss:36, in mixin `-ty-breakpoint`
       	node_modules/typi/scss/typi/_typi.scss:29, in mixin `typi`
       	src/scss/base/_typography.scss:8
        on line 30 of node_modules/typi/scss/ty/_functions.scss
>>   @if unitless($font-size) {
   ------^
```

**Comment by zellwk** [comment]
Did you have modular scale installed?

**Comment by MatthewKosloski** [comment]
Yeah, and I'm running Typi `2.3.0`.  I tried it with a custom function I made and got the same error.  [Here](https://github.com/MatthewKosloski/gulp/blob/master/src/scss/base/_typi.scss) is my repo file.  The strange thing is when I used this with Webpack, I didn't get the error. 

Thank you for your help; Typi is a phenomenal tool!

**Comment by zellwk** [comment]
Uhhh. Not too sure what's happening ><. Can you try again with V3 (Docs just updated. There's a breaking change to the typi map).

**Comment by zellwk** [comment]
Closing until further comments.

**Comment by mokorana** [comment]
I am  running in the same problem using modular-scale inside $typi. I tried different versions of modular-scale and typi. Maybe someone run into the same trouble?

```
$typi: (
  base: (
    null: (15px, 1.4),
    small: ms(2)
  )
);
```

Error: $number: ms(2) is not a number.
  @if unit($font-size) != 'px' {
