### ISSUE TITLE
Incorrect line height calculated on typi-init function

### ISSUE THREAD

**Issue by trafiq** [zellwk/typi#28]
Hi. Just starting with 3.0 and notice that when I set the following base values and output `@include typi-init;` on my HTML CSS selector:

```
$typi: (
  base: (
    null: (16px, 1.5),
    tablet: (18px),
    desktop: (20px)
  )
);
```

I don't get this as expected:

```
font-size: 100%;
line-height: 1.5em;
```
I get just this instead:
```
line-height: 1.15
```
`font-size: 100%` is missing. Also, the `line-height` shows the wrong value and is missing the `em` unit.

Any ideas what might be causing this?

**Comment by trafiq** [comment]
Apologies. I just realised my mistake. I was including `typi-init` within my HTML CSS selector as per version 2. I realise the selector is now part of the function and therefore not required.

So just this:
```
@include typi-init;
```
And not this:
```
html {
  @include typi-init;
}
```
Closed as works as expected.

**Comment by zellwk** [comment]
@trafiq 👍
