### ISSUE TITLE
Could not make typi working well with singularity

### ISSUE THREAD

**Issue by sinyayadynya** [zellwk/typi#32]
Hi,
That is some times that I'm reading your post and tried typi, which looks very interesting. But somehow, I cannot make it to work well with singularity which I'm using in all of my projects. It seems to break the default font size, and blow all the grid. 
Maybe I'm missing something. Do you have any tip about how to solve that?
Thanks for help.

**Comment by zellwk** [comment]
I don't use Singularity, so I'm not sure what's wrong.
