### ISSUE TITLE
Can't get the library to work

### ISSUE THREAD

**Issue by cywtf** [zellwk/typi#33]
I can't get this library to work.

1. `npm install typi --save-dev`
2. Copy that typi folder into my `/base` directory with the rest of my scss files 
3. Import typi in my app.scss file using `@import 'base/typi/scss/typi';`
4. Set up breakpoints and typi map using:

```
$breakpoints: (
  desktop:      1200px,
);


$typi: (
  base: (
    null: (14px, 1.4),
    desktop: (24px)
  ),
  h1: (
    null: (18px, 1.4),
    desktop: (32px)
  )
);
```

5. And then apply it to the html like this:
```
html {
	@include typi-init;
}
```

I can see typi.scss displayed in my .map file so the library is correctly imported, however nothing is displayed, no styles are applied in my html tag. Text remains unformatted. Any ideas?

**Comment by cywtf** [comment]
Oh wow, I realized now the mistake. I understood as I had to add the mixin `@include typi-init;` in the html tag while that is not anymore the case (it was in previous versions, although with a different name).

Can you make the documentation a bit more clear in that specific point?

Thanks!

**Comment by dianagasper13** [comment]
I am having the same problem and can't figure out what the issue is. Any help would be appreciated.
