### ISSUE TITLE
False mixin not found

### ISSUE THREAD

**Issue by epigeyre** [zellwk/typi#34]
Hello,

I have the following error that displays in my terminal:

    node_modules/typi/scss/private/breakpoints/_breakpoints.scss
    Error: false mixin not found
      on line 76 of node_modules/typi/scss/private/breakpoints/_breakpoints.scss
      >>  @error "#{$lib} mixin not found";`

I am using the last versions of typi and mappy-breakpoints with the following code:

    $typi-breakpoint: mappy-breakpoints;

    $breakpoints: (
      small: 600px,
      large: 1200px,
      max: 1600px
    );

**Comment by zellwk** [comment]
$typi-breakpoint: mappy-breakpoint; no s :)

**Comment by epigeyre** [comment]
Thank you. I've solved my issue, the problem had nothing to do with typi sorry! 

However, you might want to correct your article here as it is using `mappy-breakpoints` instead of `mappy-breakpoint` : [https://zellwk.com/blog/advanced-typi/](https://zellwk.com/blog/advanced-typi/)

**Comment by zellwk** [comment]
Typi got upgraded :)
