### ISSUE TITLE
Namespace your map variables

### ISSUE THREAD

**Issue by cjwd** [zellwk/typi#36]
Other libraries use variables such as breakpoints.
Consider name spacing the breakpoints map variable to avoid conflicts for example
$typi-breakpoints:

**Comment by zellwk** [comment]
Did you find a conflict in these namespaces yourself? I'm wondering cause I didn't feel that's a problem, but happy to hear more and investigate it.

**Comment by tomdowning82** [comment]
Agree with this, i use a custom breakpoint function, called '$breakpoint', which fails with this as the format is not compatible with your breakpoint.
Can I easily change the your name to $typi-breakpoints?

**Comment by zellwk** [comment]
@tomdowning82 Not right now. You need to change provide a `$breakpoint` variable for each `typi` mixin you call right now. I have yet to abstract these away. May need some time before I can get to this. But point taken. 

If you can send a pull request, that'll help out a ton.
