### ISSUE TITLE
Consider adding support for Sass MQ

### ISSUE THREAD

**Issue by cjwd** [zellwk/typi#37]
Consider adding support for Sass MQ: https://github.com/sass-mq/sass-mq which seems to have all the requirements which lead to write Mappy Breakpoints.

**Comment by riskiii** [comment]
I too would like to either see the currently active breakpoint in mappy, or add mq as an option for typi.

**Comment by zellwk** [comment]
Mind sending in a pull request?

**Comment by TommyScribble** [comment]
This is a great idea!
Just wondering if any progress has been made, as I'd love to use this in a current project that uses Sass-MQ throughout.........

**Comment by zellwk** [comment]
I'm right on time to work on this, would greatly appreciate if anyone is willing to send in a pill request.

**Comment by zellwk** [comment]
Tight*

**Comment by marijang** [comment]
or https://github.com/infinum/media-blender

**Comment by christopherdarling** [comment]
@zellwk any chance you could do a new release with this?

**Comment by zellwk** [comment]
@christopherdarling Oh shoot. I totally forgot! Let me work on it now. Thanks for the reminder!

**Comment by zellwk** [comment]
Published!

**Comment by christopherdarling** [comment]
Awesome, thanks @zellwk 👍
