### ISSUE TITLE
DEPRECATION WARNING & Invalid CSS

### ISSUE THREAD

**Issue by varius92** [zellwk/typi#38]
DEPRECATION WARNING:
`DEPRECATION WARNING on line 13 of /data/55/_andi/mhframework/webroot/less/abstracts/mixins/_grid-framework.scss: #{} interpolation near operators will be simplified
in a future version of Sass. To preserve the current behavior, use quotes:

  unquote('#{100 / $columns * $number}"%"')

You can use the sass-convert command to automatically fix most cases.`

------------------------------------------------------------------------

Invalid CSS:
`scss --no-cache --update main.scss:main.css
      error vendor/typi/private/breakpoints/_breakpoints.scss (Line 91: Invalid CSS after "...nd (min-width: ": expected expression (e.g. 1px, bold), was ")")

Process finished with exit code 1`

------------------------------------------------------------------------

Sass 3.4.24 (Selective Steve)

I only configure breakpoints and typi-base. I didn't edit nothing else.
`$typi: (
        base: (
                null: (16px, 1.4),
                small:18px,
                large: 20px
        )
) !default;`
`$breakpoints: (
        xs: 30em,
        sm: 48em,
        mg: 62em,
        lg: 75em
) !default;`
`html {
  box-sizing: border-box;
  @include typi-base();
}
`
How can i fix this?

**Comment by zellwk** [comment]
The problem lies with keys in your `$typi` and `$breakpoints`. `$typi` keys must exist in `$breakpoints`. 

$typi | $breakpoints
------|--------------
small  | sm 
large  | lg

**Comment by varius92** [comment]
o m g ... shame on me :D
But i get the same error again :(

Sry im new in Sass/SCSS... how can i use the sass-convert command?

**Comment by zellwk** [comment]
I don't use it myself. And this is probably the wrong place to ask about sass-convert
