### ISSUE TITLE
Invalid CSS output -- duplicate selectors

### ISSUE THREAD

**Issue by zreese** [zellwk/typi#40]
Using `@import "typi/scss/typi"` and `html { @include typi-base(); }`, I get this...
```
html html {
  font-size: 112.5%;
  line-height: 1.5; }
  @media all and (min-width: 540px) {
    html html {
      font-size: 100%; } }
  @media all and (min-width: 720px) {
    html html {
      font-size: 112.5%; } }
  @media all and (min-width: 960px) {
    html html {
      font-size: 112.5%; } }
  @media all and (min-width: 1366px) {
    html html {
      font-size: 125%; } }
```
Maybe a namespace conflict? Here's my map settings:
```
$breakpoints: (
	sm: 540px,
	md: 720px,
	lg: 960px,
	xl: 1366px
) !default;
$typi: (
  base: (
    null: (18px, 1.5),
    sm: 16px,
    md: 18px,
    lg: 18px,
    xl: 20px
  )
) !default;
```

**Comment by zellwk** [comment]
Did you upgrade from typi2 to typi3? Typi 3 works a little differently. You use 'typi-init' without putting it in the `html` selector.

**Comment by zreese** [comment]
Thank you, that was exactly the problem!

I just followed the tutorial [on your blog](https://zellwk.com/blog/typi/). I scanned the readme and nothing jumped out at me as off. My mistake. Maybe worth putting some text at the top of the blog post about v3 and pointing to the documentation here for people like me who just stumble across it organically.
