### ISSUE TITLE
Font face inside typi map

### ISSUE THREAD

**Issue by visualcode** [zellwk/typi#48]
Hi Zell,
is there any way to insert a font face inside Typi map?
So what I'd like to do is insert the typeface in html{} with a normal typi-base map.

Thanks

**Comment by zellwk** [comment]
Why not do this? 

```
html {
  font-family: ‘your-typeface’;
}
```

**Comment by visualcode** [comment]
That's obviously a normal solution, but if I use:
`html {
    font-family: "My Font", Arial, Helvetica, sans-serif;
}
@include typi-base ();`

I get the html property twice:

````
html {
  font-family: "My Font", Arial, Helvetica, sans-serif; }

html {
  font-size: 100%;
  line-height: 1.4; }
  @media all and (min-width: 20em) {
    html {
      font-size: 100%; } }
  @media all and (min-width: 48em) {
    html {
      font-size: 112.5%; } }
  @media all and (min-width: 75em) {
    html {
      font-size: 125%; } }
````

I'd like to insert the font-family inside a unique html {}

**Comment by zellwk** [comment]
This shouldn't be a problem if you optimize your CSS with cssnano. It'll consolidate the `html` selector declarations into one.
