### ISSUE TITLE
rename to _test.scss

### ISSUE THREAD

**Issue by tcurdt** [zellwk/typi#5]
This [file](https://github.com/zellwk/typi/blob/master/scss/test.scss) breaks my build because these two imports do not resolve:

```
@import '../bower_components/mappy-breakpoints/mappy-breakpoints';
@import '../bower_components/compass-breakpoint/stylesheets/breakpoint';
```

An easy work around is to rename the file to `_test.scss`.

**Comment by zellwk** [comment]
Ah. Don't worry about this file, go ahead and delete it. I'm going to delete it on my side too. They were just test files :)
