### ISSUE TITLE
How can this be ported?

### ISSUE THREAD

**Issue by strarsis** [zellwk/typi#50]
This gist shows how to use modular-scale with compass vertical rhythm:
https://gist.github.com/mirisuzanne/3601836
What exactly happens there? Isn't this basically what typi does out of the box?

Edit: I just noticed that you are also the author of (awesome) 
[vertical-rhythms-without-compass](https://github.com/zellwk/vertical-rhythms-without-compass) and that you recommend typi (this) instead of it. 

If I wanted to port the styles in the gist to typi, would it be just a matter of 
configuring the breakpoints and (modular) scales?

**Comment by zellwk** [comment]
API has changed slightly, but you can follow this general approach to configure breakpoints and scales: https://zellwk.com/blog/modular-scale/
