### ISSUE TITLE
Show vertical grid?

### ISSUE THREAD

**Issue by strarsis** [zellwk/typi#51]
Compass Vertical Rhythm allows to [show the underlying grid](http://compass-style.org/reference/compass/layout/grid_background/).
Can this be added to `typi`, too? On the other hand, I read somewhere here that the vertical grid never truly aligns on all browsers, showing one being more or less pointless?

**Comment by zellwk** [comment]
Nope. There's no point. Read this: https://zellwk.com/blog/web-typography-broken/
