### ISSUE TITLE
Calculate height

### ISSUE THREAD

**Issue by strarsis** [zellwk/typi#52]
Can I use typi for calculating the height of a line (or amount of lines), 
including extra height by `line-height`?
I want to add `margin` to an element to compensate for the height of 
a (for some items) missing element below.

**Comment by zellwk** [comment]
Use the `vr` function.

**Comment by strarsis** [comment]
@zellwk: Does it make sense to use `vr` also for non-vertical things? Like a horizontal `margin` or `padding`?
Or should modular-scale (`ms`) be used directly for non-vertical properties?

**Comment by zellwk** [comment]
Yes.
