### ISSUE TITLE
Line-Height by Percentage

### ISSUE THREAD

**Issue by MikeiLL** [zellwk/typi#58]
Hey Zell.

I need a "negative" `line-height`. I tried using a percentage within the map:

      null: (ms(0), 80%),
      small: (ms(0), 80%),
      medium: (ms(0), 80%),
      large: (ms(0), 80%)

That doesn't seem to work.

Also tried using a fraction in a `vr()`.

    .my_DOM_el  {
      line-height: vr(0.5); 
    }

I am probably missing something. Can you help?

**Comment by zellwk** [comment]
`line-height` is programmed as a unitless value in Typi. Try this: 

```
null: (ms(0), -0.5),
```

**Comment by MikeiLL** [comment]
Perfect, my man. TY.
