### ISSUE TITLE
Declaring values in $typi map

### ISSUE THREAD

**Issue by codedblack** [zellwk/typi#8]
I was wondering do you have to declare all the values in the $typi map even if you decide to not use other breakpoints. When I added a new value on the $h1-map using the large breakpoint I kept getting an error. But when i put a large breakpoint on the $typi map i didn't get an error.

This is file I'm declaring the breakpoints (_breakpoints.scss)

```
$breakpoints: (
 small: 480px,
 medium: 768px,
 general: 960px,
 large: 1280px
);

```

This is the file I'm declaring the typography (_typography.scss)

```
$breakpoints: () !default;
$typi-breakpoint: null !default;
$breakpoint-to-ems: true;

$typi: (
 null: (16px, 20px),
 large: (18px, 22px) // when added no error
);

$p-map: (
 null: (15px, 27px)
);

$h1-map: (
 null: (32px, 40px),
 large: (41px, 49px) // new large value example
);
```

This is the error message I'm getting:

```
Message:
sass/variables/_typography.scss
Error: unclosed parenthesis
on line 21 of sass/variables/_typography.scss
>>   large: (41px, 49px)

Details:
formatted: Error: unclosed parenthesis
on line 21 of sass/variables/_typography.scss
>>   large: (41px, 49px)

column: 3
line: 21
file: /Users/codedblack/Documents/Laboratory/VVV/www/macclesfield_hc/htdocs/wp-content/themes/macclesfield_hc_vf/sass/variables/_typography.scss
status: 1
messageFormatted: sass/variables/_typography.scss
Error: unclosed parenthesis
on line 21 of sass/variables/_typography.scss
>>   large: (41px, 49px)

messageOriginal: unclosed parenthesis
relativePath: sass/variables/_typography.scss
```

Thanks

**Comment by zellwk** [comment]
Hey, I can't replicate the error you're getting. Can you 1) make sure you're on the latest version of Typi? I've fixed this specific error previously. 2) if it doesn't work, send me an email with a project that has this error.

**Comment by codedblack** [comment]
Thanks for the advice. I'll look at this over the weekend and let you know how it goes.

**Comment by zellwk** [comment]
Fixed this. Test it out with the latest patch and let me know if it worked for you

**Comment by codedblack** [comment]
That's great. All working now and thanks for the swift fix.
